/**
 * Platform-agnostic browser automation contract.
 *
 * Every job platform adapter must implement PlatformAutomator.
 * The backend never contains platform-specific logic beyond the adapter itself.
 */

import type { AutomationPlatform, AutomationStep } from "@shared/types";

export interface StepReporter {
  /** Report the current automation step and progress (0–100) */
  report(
    step: AutomationStep,
    progress: number,
    message?: string,
  ): Promise<void>;
  /** Capture and store a screenshot for the current task */
  screenshot(label: string): Promise<string | null>;
  /** Append a structured log entry for the current task */
  log(
    level: "info" | "warn" | "error",
    message: string,
    meta?: unknown,
  ): Promise<void>;
}

export interface JobApplicationInput {
  jobUrl: string;
  jobTitle: string;
  employer: string;
  jobDescription: string | null;
  resumePath: string | null;
  coverLetter: string | null;
  /** Answers generated by AI for free-text questions */
  aiAnswers: Map<string, string>;
}

export interface ApplicationResult {
  success: boolean;
  confirmationNumber?: string;
  confirmationUrl?: string;
  errorMessage?: string;
}

/**
 * Every platform adapter implements this interface.
 * The engine calls these methods in order.
 */
export interface PlatformAutomator {
  readonly platform: AutomationPlatform;
  readonly label: string;

  /** Log into the platform, reusing an existing session when available */
  login(
    username: string,
    password: string,
    reporter: StepReporter,
  ): Promise<void>;

  /** Search for jobs matching the given keywords and location */
  searchJobs(
    keywords: string,
    location: string,
    reporter: StepReporter,
  ): Promise<string[]>;

  /** Extract job details from a job listing URL */
  extractJob(
    jobUrl: string,
    reporter: StepReporter,
  ): Promise<Partial<JobApplicationInput>>;

  /** Navigate to the application form */
  navigateToApply(jobUrl: string, reporter: StepReporter): Promise<void>;

  /** Upload a resume file to the form */
  uploadResume(resumePath: string, reporter: StepReporter): Promise<void>;

  /** Fill in all visible form fields */
  fillForm(input: JobApplicationInput, reporter: StepReporter): Promise<void>;

  /** Answer AI-generated screening questions */
  answerQuestions(
    aiAnswers: Map<string, string>,
    reporter: StepReporter,
  ): Promise<void>;

  /** Submit the completed application */
  submit(reporter: StepReporter): Promise<void>;

  /** Verify the application was accepted by the platform */
  verify(reporter: StepReporter): Promise<ApplicationResult>;

  /** Gracefully log out — only called when explicitly requested */
  logout(reporter: StepReporter): Promise<void>;

  /** Full apply workflow in one call — the engine delegates to this */
  apply(
    input: JobApplicationInput,
    reporter: StepReporter,
  ): Promise<ApplicationResult>;
}

export interface BrowserEngine {
  /** Get or create a Playwright browser context for the given profile directory */
  getContext(profileDir: string): Promise<import("playwright").BrowserContext>;
  /** Close a specific context */
  closeContext(profileDir: string): Promise<void>;
  /** Shut down all contexts */
  shutdown(): Promise<void>;
}
